accounts: 
  - # 账号, 现只支持 QQ 数字账号
    account: 2651884058
    password: 
      # 密码种类, 可选 PLAIN 或 MD5
      kind: MD5
      # 密码内容, PLAIN 时为密码文本, MD5 时为 16 进制
      value: a76f065ad99e491f85fc56d1f8437d75
    # 账号配置. 可用配置列表 (注意大小写):
    # "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH"
    # "device": "device.json"
    configuration: 
      protocol: ANDROID_PHONE
      device: device.json